### POST /{{newAccountId}}/devices (Register Device)
POST {{host}}/accounts/{{newAccountId}}/devices
Content-Type: application/vnd.bose.streaming-v1.2+xml
Authorization: Bearer {{authToken}}

<?xml version="1.0" encoding="UTF-8" ?>
<device deviceid="{{deviceId}}">
    <name>{{deviceName}}</name>
</device>

> {%
    client.test("Device registered successfully", function() {
        client.assert(response.status === 200 || response.status === 201, "Response status is not 200 or 201");
        const doc = response.body;
        const device = doc.getElementsByTagName("device")[0];
        client.assert(device !== undefined, "Response body should contain <device>");
        client.assert(device.getAttribute("deviceid") === client.variables.environment.get("deviceId"), "Response body should contain the deviceId");
    });
%}
