### DELETE /streaming/account/{{accountId}}/device/{{deviceId}} (Unregister Device)
DELETE {{host}}/streaming/account/{{accountId}}/device/{{deviceId}}
Authorization: Bearer {{token}}

> {%
    client.test("Device unregistered successfully", function() {
        client.assert(response.status === 200, "Response status is not 200");
    });
%}
